freight-team/freight

lib/freight/apt.sh

Signed-off-by: Youhei SASAKI <uwabami@gfd-dennou.org>
---
Patch is from the uwabami-freight fork (per https://github.com/rcrowley/freight/issues/66), with whitespace fixed.

Add Date:, Valid-Until

---

bin/freight-cache
bin/freight-init
etc/freight.conf.example
lib/freight/apt.sh
man/man1/freight-cache.1
man/man1/freight-cache.1.ronn
man/man1/freight-init.1
man/man1/freight-init.1.ronn
man/man5/freight.5
man/man5/freight.5.ronn

The GPG config option and associated command arguments now accept
multiple GPG keys, which are all used to sign the Release file.  This
makes it easier to roll keys, similar to the Debian archives which are
signed with multiple release keys.

Sign apt's Release file with multiple GPG keys

---

bin/freight-cache
bin/freight-init
etc/freight.conf.example
lib/freight/apt.sh

Using a space-separated string of GPG UIDs is compatible with non-bash,
POSIX compatible shells such as dash.
Fixes #8

Replace bash-only GPG UID array with string

---

bin/freight-add
lib/freight/apt.sh

handle .tar.bz2 and .tar.lzma files

---

lib/freight/apt.sh

freight-cache produces multiple lines warnings (proportional to the size of cache):
`find: cannot delete [...]/cache/pool/[...]: Directory not empty`
The behavior is correct. This directories should only be removed, when they are empty after removing old packages. Thus the warnings are erroneous.

Fixed warnings about not removable non-empty folders in apt_clean()

---

.travis.yml
bin/freight
bin/freight-add
bin/freight-cache
bin/freight-clear-cache
lib/freight/apt.sh
lib/freight/conf.sh

Unfortunately, shellcheck is only available as a package in Ubuntu/trusty, requiring some loops to jump through to get everything working.
Another thing is that I have my vi configured to not produce hard tabs and use two space indenting, which makes the diff looking odd now, what are the opinions on this?

shellcheck testing & fixes

---

lib/freight/apt.sh

Can be checked by running the string through `date -d '...' +%s`.

Fix Valid-Until date to be a valid, parsable date

---

bin/freight-cache
etc/freight.conf.example
lib/freight/apt.sh
man/man1/freight-cache.1
man/man1/freight-cache.1.ronn
man/man5/freight.5
man/man5/freight.5.ronn

The Apt project have deprecated SHA1 for signing repos and will be removing support for it at the start of next year: https://wiki.debian.org/Teams/Apt/Sha1Removal
From Ubuntu 16.04 onward, a warning message for all repos signed with SHA1 will be displayed when apt-get is run:
The repository is insufficiently signed by key KEYID (weak digest)
I have added a new configuration element (GPG_DIGEST_ALGO) to freight which adds support for telling GPG that we want to use SHA256 or SHA512. I have left the defaults alone as I'm not sure if there are any side effects to dropping SHA1.
I have also added support for the SHA512 field in Release and Package files generated by Freight.

Add ability to configure digest algorithm used to sign repository.

---

bin/freight-cache
test/apt_add.bats
test/apt_cache.bats

Resubmitted from https://github.com/rcrowley/freight/pull/68, with extra tests and another trivial fix that was required to make them pass (when VARLIB has no trailing /).

Handle the scenario where $VARLIB is a symlink

---

man/man1/freight-init.1
man/man1/freight-init.1.ronn

Fix formatting of paths, fix missing supported arguments and fix names
of existing libdir/cachedir args.

Refresh freight-init man page

---

lib/freight/apt.sh

apt- 1.3 arrived in Debian/testing today and I'm getting the following warnings:
```
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/space.kvedulv.de_apt_dists_stretch_Release
W: The repository 'http://space.kvedulv.de/apt stretch Release' provides only weak security information.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
The first line is from the server having the local time zone (CEST in my case) set and the other three ones from the `Valid-Date` field not being in UTC.

use UTC timezone for Date fields

---

Makefile

When trying to build a traditional debian package it is quite annoying
that `make clean` removes the debian directory.

This changes the destdir for fpm based builds from debian to deb.

---

README.md

The location of the freight apt repository has changed on the webserver. While compatibility links are in place, new users should be pointed to the correct, new URL.

Change freight apt repository URL to a non-deprecated one

---

Makefile

#44 Force install of the gzip'd man pages.
This lets the install work on second and subsequent attempts as gzip would previously fail due to the existing man pages.

#44 Force install of the gzip'd man pages.

---

lib/freight/apt.sh

As described here[1], if pubring.gpg already exists, .kbx format will
not be used. This fixes tests for new GPG versions that otherwise
failed due to `pubring.gpg` not existing after `gpg --import` into
`$TMP/gpg`.
1: https://www.gnupg.org/faq/whats-new-in-2.1.html
Without this commit:
$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
$ gpg --version
gpg (GnuPG) 2.1.17
$ git log -n 1
commit 4f412fa6daded0cac6b8f9b4f5c643343a9cb36f
Author: Stephen Ryan <ryaner@users.noreply.github.com>
Date:   Tue Nov 22 09:19:21 2016 +0000
Let install-man task work on second and subsequent attempts
gzip would previously fail …

Prevent GPG >= 2.1 from using .kbx pubring format during import

---

etc/freight.conf.example
lib/freight/apt.sh
lib/freight/conf.sh
man/man5/freight.5

These fields are necessary to create a release like `jessie-backports`.

Learn NotAutomatic and ButAutomaticUpgrades release fields

---

lib/freight/apt.sh

Please see https://wiki.archlinux.org/index.php/GnuPG#Unattended_passphrase for gpg's `--pinentry loopback` option.

Support gpg2 in freight cache passphrase file option

---

README.md

Added follow symlink requirement to the webserver configuration. Some web servers (Apache) don't allow it by default.

Added missing symlink requirement

---

bin/freight-add
lib/freight/apt.sh
man/man1/freight-add.1
man/man1/freight-add.1.ronn

Adds support for the `.ddeb` extension, currently in use by Ubuntu for [packages with debug symbols](https://wiki.ubuntu.com/AptElfDebugSymbols).

Support 'ddeb' file extension

---

test/freight_helpers.bash

If the system already has a freight.conf with another arch, this
will make the "freight-cache builds per-component Release file"
test fail as it awaits "binary-amd64" folder.

Tests: initialize default archs

---

test/apt_helpers.bash

Export our key so apt can use it as trusted key.
Create an empty status file.

Tests: fix apt-get errors

---

.github/workflows/freight-tests.yml
test/freight_helpers.bash

GitHub repository needs two secrets and a passphrase that will be
imported before the make check can be invoked:
- FREIGHT_GPG_KEY_FIRST
- FREIGHT_GPG_KEY_SECOND
- FREIGHT_KEY_PASSWD
To avoid interactive password request from apt a passphrase file
will be used.

Port CI to GitHub Actions

---

.dir-locals.el

This instructs emacs to use an indentation of 4 spaces to avoid issues with
unnecessary reformatting after changes.

Add .dir-locals.el for setting sh-basic-offset

---

README.md

root@test:~# git clone git://github.com/freight-team/freight.git
Cloning into 'freight'...
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

Update read me to reflect support git protocol changes

---

bin/freight-add
lib/freight/apt.sh
man/man1/freight-add.1.ronn

udeb files are stripped down deb files for use by the DebianInstaller.

Add udeb file support

---

test/apt_add.bats
test/apt_cache.bats
test/apt_cache_source.bats
test/apt_helpers.bash
test/freight_helpers.bash

Add double quotes and replace the deprecated "egrep" with "grep -E".

CI: perform test scripts linting

---

.github/workflows/freight-man-pages.yml

This workflow installs `ronn` prior to generating the manpages.

Add a workflow for the manpage generation

---

bin/freight-cache

`FIND_L` variable defines the -L parameter to the `find` command. Hence it should not be quoted. Otherwise, `find` command produces the following error:
`find: ‘’: No such file or directory`
Fixes #138

bin/freight-cache: don't quote the FIND_L variable
